FROM oracle/database:12.2.0.1-ee

MAINTAINER Thanasis Sergouniotis <thanasis.sergouniotis@intrasoft-intl.com>

ARG ORACLE_SID
ARG ORACLE_PDB
ARG ORACLE_PWD

ENV ORACLE_SID ${ORACLE_SID}
ENV ORACLE_PDB ${ORACLE_PDB}
ENV ORACLE_PWD ${ORACLE_PWD}
