version: '3.6'
services:
  pdmt-db:
    image: registry/oracle-db:12.2.0.1
    container_name: oradata
    volumes:
      - oradata:/opt/oracle/oradata # persistent oracle database data.
    networks:
      oranet:
        aliases:
          - oradb
    ports:
      - 1521:1521
    healthcheck:
      test: "tnsping localhost:1521"
networks:
  oranet:
volumes:
  oradata:
